# Generated by Django 4.2.8 on 2026-01-03 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SorobanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('difficulty', models.CharField(choices=[('beginner', 'Începător'), ('intermediate', 'Intermediar'), ('advanced', 'Avansat'), ('expert', 'Expert')], max_length=20, verbose_name='Dificultate')),
                ('operation_type', models.CharField(choices=[('addition', 'Adunare'), ('subtraction', 'Scădere'), ('multiplication', 'Înmulțire'), ('division', 'Împărțire'), ('mixed', 'Combinat')], max_length=20, verbose_name='Tip Operație')),
                ('number_count', models.IntegerField(default=5, verbose_name='Număr de Probleme')),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True, verbose_name='Limită Timp (secunde)')),
                ('min_number', models.IntegerField(default=1, verbose_name='Număr Minim')),
                ('max_number', models.IntegerField(default=100, verbose_name='Număr Maxim')),
                ('points_per_correct', models.IntegerField(default=10, verbose_name='Puncte per Răspuns Corect')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercițiu Soroban',
                'verbose_name_plural': 'Exerciții Soroban',
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SorobanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_attempted', models.IntegerField(default=0, verbose_name='Probleme Încercate')),
                ('problems_correct', models.IntegerField(default=0, verbose_name='Răspunsuri Corecte')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Start')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data Finalizare')),
                ('total_time_seconds', models.IntegerField(blank=True, null=True, verbose_name='Timp Total (secunde)')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Puncte Câștigate')),
                ('answers_detail', models.JSONField(blank=True, default=list, verbose_name='Detalii Răspunsuri')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='soroban.sorobanexercise', verbose_name='Exercițiu')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='soroban_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Elev')),
            ],
            options={
                'verbose_name': 'Sesiune Soroban',
                'verbose_name_plural': 'Sesiuni Soroban',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SorobanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1, verbose_name='Nivel Curent')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Total Sesiuni')),
                ('total_problems_solved', models.IntegerField(default=0, verbose_name='Total Probleme Rezolvate')),
                ('total_correct_answers', models.IntegerField(default=0, verbose_name='Total Răspunsuri Corecte')),
                ('total_points', models.IntegerField(default=0, verbose_name='Total Puncte')),
                ('best_accuracy', models.FloatField(default=0.0, verbose_name='Cea mai Bună Acuratețe (%)')),
                ('fastest_problem_time', models.IntegerField(blank=True, null=True, verbose_name='Cel mai Rapid Timp (secunde)')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='Realizări')),
                ('last_practice_date', models.DateField(blank=True, null=True, verbose_name='Ultima Dată Practică')),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='soroban_progress', to=settings.AUTH_USER_MODEL, verbose_name='Elev')),
            ],
            options={
                'verbose_name': 'Progres Soroban',
                'verbose_name_plural': 'Progres Soroban',
            },
        ),
    ]
