// Test script to verify large negative numbers (-6, -7, -8, -9) appear in direct-to-9 exercises
// This simulates generating exercises and checking the distribution

// Simulate exercises that should be generated with the fix
const testExercises = [];

// Generate 50 test exercises with various patterns expected
for (let i = 0; i < 50; i++) {
    // These would be generated by the actual generator
    // For now, we'll analyze the existing hardcoded exercises
}

// Use the existing analyze_exercises.js data as baseline
console.log('Expected behavior after fix:');
console.log('- From value 6: can subtract 6 (operations: 6-6)');
console.log('- From value 7: can subtract 6, 7 (operations: 7-6, 7-7)');
console.log('- From value 8: can subtract 6, 7, 8 (operations: 8-6, 8-7, 8-8)');
console.log('- From value 9: can subtract 6, 7, 8, 9 (operations: 9-6, 9-7, 9-8, 9-9)');
console.log('');
console.log('Running analyze_exercises.js to see current distribution:');
console.log('');
