# Generated by Django 4.2.8 on 2026-01-03 22:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume Grupă')),
                ('weekday', models.IntegerField(choices=[(0, 'Luni'), (1, 'Marți'), (2, 'Miercuri'), (3, 'Joi'), (4, 'Vineri'), (5, 'Sâmbătă'), (6, 'Duminică')], verbose_name='Zi Săptămână')),
                ('start_time', models.TimeField(verbose_name='Ora Start')),
                ('duration_minutes', models.IntegerField(default=90, verbose_name='Durată (minute)')),
                ('start_date', models.DateField(verbose_name='Data Start')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Sfârșit')),
                ('max_occurrences', models.IntegerField(blank=True, help_text='Lasă gol pentru recurență nelimitată', null=True, verbose_name='Număr Maximum Lecții')),
                ('max_students', models.IntegerField(default=8, verbose_name='Număr Maxim Elevi')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Curs')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_groups', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Grupă',
                'verbose_name_plural': 'Grupe',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Ora Start')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Ora Sfârșit')),
                ('status', models.CharField(choices=[('scheduled', 'Programată'), ('ongoing', 'În Desfășurare'), ('completed', 'Finalizată'), ('cancelled', 'Anulată')], default='scheduled', max_length=20, verbose_name='Status')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='Subiect')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('homework', models.TextField(blank=True, verbose_name='Temă pentru Acasă')),
                ('materials', models.FileField(blank=True, null=True, upload_to='lesson_materials/', verbose_name='Materiale')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Notițe Profesor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teacher_platform.group', verbose_name='Grupă')),
            ],
            options={
                'verbose_name': 'Lecție',
                'verbose_name_plural': 'Lecții',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Data Asignare')),
                ('due_date', models.DateField(verbose_name='Termen Limită')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Fișier Atașat')),
                ('max_points', models.IntegerField(default=100, verbose_name='Punctaj Maxim')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher_platform.group', verbose_name='Grupă')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='teacher_platform.lesson', verbose_name='Lecție Asociată')),
            ],
            options={
                'verbose_name': 'Temă',
                'verbose_name_plural': 'Teme',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField(auto_now_add=True, verbose_name='Data Înrolare')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('lessons_attended', models.IntegerField(default=0, verbose_name='Lecții Prezenți')),
                ('lessons_missed', models.IntegerField(default=0, verbose_name='Lecții Absente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher_platform.group', verbose_name='Grupă')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_groups', to=settings.AUTH_USER_MODEL, verbose_name='Elev')),
            ],
            options={
                'verbose_name': 'Elev în Grupă',
                'verbose_name_plural': 'Elevi în Grupe',
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Prezent')),
                ('notes', models.TextField(blank=True, verbose_name='Observații')),
                ('performance_rating', models.IntegerField(blank=True, help_text='Cum a performat elevul în această lecție', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Evaluare Performanță (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teacher_platform.lesson', verbose_name='Lecție')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Elev')),
            ],
            options={
                'verbose_name': 'Prezență',
                'verbose_name_plural': 'Prezențe',
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, verbose_name='Răspuns Text')),
                ('file_response', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Fișier Răspuns')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Punctaj Obținut')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback Profesor')),
                ('is_graded', models.BooleanField(default=False, verbose_name='Evaluat')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Predare')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Data Evaluare')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher_platform.assignment', verbose_name='Temă')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Elev')),
            ],
            options={
                'verbose_name': 'Predare Temă',
                'verbose_name_plural': 'Predări Teme',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
