# Generated by Django 5.2.10 on 2026-01-15 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_module_lessontemplate"),
        ("teacher_platform", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="code",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Generat automat: CURS-MODUL-NUMĂR",
                max_length=100,
                unique=True,
                verbose_name="Cod Grupă",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="created_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Data la care a fost creată grupa (editabilă)",
                verbose_name="Data Creare",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="courses.location",
                verbose_name="Locație",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="module",
            field=models.ForeignKey(
                blank=True,
                help_text="Modulul din curs pe care îl parcurge această grupă",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="courses.module",
                verbose_name="Modul",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Lecția template din modul (opțional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_lessons",
                to="courses.lessontemplate",
                verbose_name="Șablon Lecție",
            ),
        ),
        migrations.CreateModel(
            name="LessonNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        help_text="Notițe și observații pentru această lecție",
                        verbose_name="Notițe",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_notes",
                        to="teacher_platform.group",
                        verbose_name="Grupă",
                    ),
                ),
                (
                    "lesson_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_notes",
                        to="courses.lessontemplate",
                        verbose_name="Șablon Lecție",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notiță Lecție",
                "verbose_name_plural": "Notițe Lecții",
                "unique_together": {("lesson_template", "group", "teacher")},
            },
        ),
    ]
