# Generated by Django 5.2.10 on 2026-07-13 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "teacher_platform",
            "0002_group_code_group_created_date_group_location_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulatorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Temă de casă", max_length=200, verbose_name="Titlu"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="De la data")),
                ("end_date", models.DateField(verbose_name="Până la data")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creată la"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulator_assignments",
                        to="teacher_platform.group",
                        verbose_name="Grupă",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "student"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_simulator_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elev (doar pentru temă personalizată)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temă Simulatoare",
                "verbose_name_plural": "Teme Simulatoare",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulatorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Ordine"),
                ),
                (
                    "simulator",
                    models.CharField(
                        choices=[
                            ("anzan", "Calcul mental (Anzan)"),
                            ("flashcards", "Cartonașe flash"),
                            ("flashcard-exercises", "Exerciții cu cartonașe"),
                            ("worksheet", "Fișă de lucru (PDF printabil)"),
                        ],
                        max_length=30,
                        verbose_name="Simulator",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(default=dict, verbose_name="Setări simulator"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("count", "Număr de exerciții"),
                            ("minutes", "Minute de lucru"),
                        ],
                        default="count",
                        max_length=10,
                        verbose_name="Tip țintă",
                    ),
                ),
                (
                    "target_value",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Valoare țintă"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="teacher_platform.simulatorassignment",
                        verbose_name="Temă",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sarcină Simulator",
                "verbose_name_plural": "Sarcini Simulator",
                "ordering": ["assignment", "order"],
            },
        ),
        migrations.CreateModel(
            name="SimulatorTaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_exercises",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exerciții rezolvate"
                    ),
                ),
                (
                    "correct",
                    models.PositiveIntegerField(default=0, verbose_name="Corecte"),
                ),
                (
                    "incorrect",
                    models.PositiveIntegerField(default=0, verbose_name="Greșite"),
                ),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Timp lucrat (sec)"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Finalizată"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizată la"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizat la"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulator_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elev",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="teacher_platform.simulatortask",
                        verbose_name="Sarcină",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezultat Sarcină",
                "verbose_name_plural": "Rezultate Sarcini",
                "unique_together": {("task", "student")},
            },
        ),
    ]
