# Generated by Django 5.2.10 on 2026-07-14 05:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0003_simulatorassignment_simulatortask_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulatortaskresult",
            options={
                "verbose_name": "Rezultat Sarcină (zi)",
                "verbose_name_plural": "Rezultate Sarcini (zile)",
            },
        ),
        migrations.AlterUniqueTogether(
            name="simulatortaskresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="simulatortaskresult",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Ziua"
            ),
        ),
        migrations.AlterField(
            model_name="simulatortask",
            name="simulator",
            field=models.CharField(
                choices=[
                    ("anzan", "Calcul mental (Anzan)"),
                    ("flashcards", "Cartonașe flash"),
                    ("flashcard-exercises", "Exerciții"),
                    ("worksheet", "Fișă de lucru"),
                ],
                max_length=30,
                verbose_name="Simulator",
            ),
        ),
        migrations.AlterField(
            model_name="simulatortaskresult",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Finalizată (ziua)"),
        ),
        migrations.AlterUniqueTogether(
            name="simulatortaskresult",
            unique_together={("task", "student", "date")},
        ),
        migrations.CreateModel(
            name="SimulatorPracticeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulator",
                    models.CharField(
                        choices=[
                            ("anzan", "Calcul mental (Anzan)"),
                            ("flashcards", "Cartonașe flash"),
                            ("flashcard-exercises", "Exerciții"),
                            ("worksheet", "Fișă de lucru"),
                        ],
                        max_length=30,
                        verbose_name="Simulator",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Ziua"
                    ),
                ),
                (
                    "exercises",
                    models.PositiveIntegerField(default=0, verbose_name="Exerciții"),
                ),
                (
                    "correct",
                    models.PositiveIntegerField(default=0, verbose_name="Corecte"),
                ),
                (
                    "incorrect",
                    models.PositiveIntegerField(default=0, verbose_name="Greșite"),
                ),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Timp (sec)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizat la"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elev",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antrenament Liber (zi)",
                "verbose_name_plural": "Antrenamente Libere (zile)",
                "unique_together": {("student", "simulator", "date")},
            },
        ),
    ]
