# Generated by Django 5.2.10 on 2026-07-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0004_alter_simulatortaskresult_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="lesson_type",
            field=models.CharField(
                choices=[("fizic", "Fizic"), ("online", "Online")],
                default="fizic",
                max_length=10,
                verbose_name="Tip Lecție",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Link-ul de Zoom/Google Meet pentru grupele online (trimis părinților)",
                verbose_name="Link Videoconferință",
            ),
        ),
    ]
