# Generated by Django 5.2.10 on 2026-07-27 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0005_group_lesson_type_group_meeting_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Pornită la"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Închisă la"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="teacher_platform.group",
                        verbose_name="Grupă",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_sessions",
                        to="teacher_platform.lesson",
                        verbose_name="Lecție programată (opțional)",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecție Live",
                "verbose_name_plural": "Lecții Live",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Ordine"),
                ),
                (
                    "simulator",
                    models.CharField(
                        choices=[
                            ("anzan", "Calcul mental (Anzan)"),
                            ("flashcards", "Cartonașe flash"),
                            ("flashcard-exercises", "Exerciții"),
                            ("worksheet", "Fișă de lucru"),
                        ],
                        max_length=30,
                        verbose_name="Simulator",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(default=dict, verbose_name="Setări simulator"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("count", "Număr de exerciții"),
                            ("minutes", "Minute de lucru"),
                        ],
                        default="count",
                        max_length=10,
                        verbose_name="Tip țintă",
                    ),
                ),
                (
                    "target_value",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Valoare țintă"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Alocată la"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="teacher_platform.livesession",
                        verbose_name="Sesiune",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "student"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_live_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elev (doar pentru sarcină individuală)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sarcină Live",
                "verbose_name_plural": "Sarcini Live",
                "ordering": ["session", "order"],
            },
        ),
        migrations.CreateModel(
            name="LiveParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Conectat la"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Văzut ultima dată"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elev",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="teacher_platform.livesession",
                        verbose_name="Sesiune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant Live",
                "verbose_name_plural": "Participanți Live",
                "unique_together": {("session", "student")},
            },
        ),
        migrations.CreateModel(
            name="LiveTaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_exercises",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exerciții rezolvate"
                    ),
                ),
                (
                    "correct",
                    models.PositiveIntegerField(default=0, verbose_name="Corecte"),
                ),
                (
                    "incorrect",
                    models.PositiveIntegerField(default=0, verbose_name="Greșite"),
                ),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Timp lucrat (sec)"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Finalizată"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizată la"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizat la"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elev",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="teacher_platform.livetask",
                        verbose_name="Sarcină",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezultat Sarcină Live",
                "verbose_name_plural": "Rezultate Sarcini Live",
                "unique_together": {("task", "student")},
            },
        ),
    ]
