# Generated by Django 5.2.10 on 2026-07-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "teacher_platform",
            "0006_livesession_livetask_liveparticipant_livetaskresult",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="livetaskresult",
            name="exercise_log",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Istoric exerciții"
            ),
        ),
    ]
