# Generated by Django 5.2.10 on 2026-08-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_lessonmilestone"),
        ("teacher_platform", "0007_livetaskresult_exercise_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonMilestoneProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="Bifat")),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bifat la"
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestone_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bifat de",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_progress",
                        to="teacher_platform.group",
                        verbose_name="Grupă",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_progress",
                        to="courses.lessonmilestone",
                        verbose_name="Milestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progres Milestone",
                "verbose_name_plural": "Progres Milestones",
                "unique_together": {("group", "milestone")},
            },
        ),
    ]
