# Generated by Django 5.2.10 on 2026-08-04 06:21
# Editat manual: GroupStudent -> Enrollment se face prin RenameModel
# (păstrează datele și cheile străine existente), NU prin Delete + Create.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0008_lessonmilestoneprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Redenumire model (non-distructiv: păstrează rândurile și FK-urile) ---
        migrations.RenameModel(
            old_name="GroupStudent",
            new_name="Enrollment",
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Înscriere",
                "verbose_name_plural": "Înscrieri",
            },
        ),
        # --- Câmpuri noi pe Enrollment: status, end_date + mixin Airtable ---
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("inscris", "Înscris"),
                    ("inactiv", "Inactiv"),
                    ("retras", "Retras"),
                    ("finalizat", "Finalizat"),
                ],
                db_index=True,
                default="inscris",
                max_length=20,
                verbose_name="Status Înscriere",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Data la care înscrierea a fost încheiată (din Airtable).",
                null=True,
                verbose_name="Data Sfârșit Înscriere",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID-ul înregistrării din Airtable (recXXXXXXXXXXXXXX). Cheie de upsert.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Airtable Record ID",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="airtable_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "În așteptare"),
                    ("synced", "Sincronizat"),
                    ("error", "Eroare"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status sincronizare",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="sync_error",
            field=models.TextField(
                blank=True, verbose_name="Ultima eroare de sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Arhivat (dispărut din Airtable)",
            ),
        ),
        # --- Attendance: mixin Airtable + câmpuri de execuție ---
        migrations.AddField(
            model_name="attendance",
            name="absenta_anuntata",
            field=models.BooleanField(default=False, verbose_name="Absență anunțată"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID-ul înregistrării din Airtable (recXXXXXXXXXXXXXX). Cheie de upsert.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Airtable Record ID",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="airtable_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="genereaza_recuperare",
            field=models.BooleanField(
                default=False, verbose_name="Generează recuperare"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Arhivat (dispărut din Airtable)",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="sync_error",
            field=models.TextField(
                blank=True, verbose_name="Ultima eroare de sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "În așteptare"),
                    ("synced", "Sincronizat"),
                    ("error", "Eroare"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status sincronizare",
            ),
        ),
        # --- Group: cod grupă Airtable + mixin ---
        migrations.AddField(
            model_name="group",
            name="airtable_cod_grupa",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Codul grupei din Airtable (cheia de business din tabelul Grupe).",
                max_length=100,
                verbose_name="Cod Grupa (Airtable)",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID-ul înregistrării din Airtable (recXXXXXXXXXXXXXX). Cheie de upsert.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Airtable Record ID",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="airtable_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Arhivat (dispărut din Airtable)",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="sync_error",
            field=models.TextField(
                blank=True, verbose_name="Ultima eroare de sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "În așteptare"),
                    ("synced", "Sincronizat"),
                    ("error", "Eroare"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status sincronizare",
            ),
        ),
        # --- Lesson: takeaways + mixin ---
        migrations.AddField(
            model_name="lesson",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID-ul înregistrării din Airtable (recXXXXXXXXXXXXXX). Cheie de upsert.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Airtable Record ID",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="airtable_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Arhivat (dispărut din Airtable)",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_takeaways",
            field=models.TextField(
                blank=True,
                help_text="Rezumatul a ceea ce s-a parcurs efectiv la lecție.",
                verbose_name="Ce s-a lucrat (takeaways)",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="sync_error",
            field=models.TextField(
                blank=True, verbose_name="Ultima eroare de sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "În așteptare"),
                    ("synced", "Sincronizat"),
                    ("error", "Eroare"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status sincronizare",
            ),
        ),
        # --- Attendance -> Enrollment FK (după redenumire) ---
        migrations.AddField(
            model_name="attendance",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="teacher_platform.enrollment",
                verbose_name="Înscriere",
            ),
        ),
    ]
