# Generated by Django 5.2.10 on 2026-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0009_attendance_absenta_anuntata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("activ", "Activ"),
                    ("inactiv", "Inactiv"),
                    ("finalizat", "Finalizat"),
                ],
                db_index=True,
                default="activ",
                max_length=20,
                verbose_name="Status Înscriere",
            ),
        ),
    ]
