# Generated by Django 5.2.10 on 2026-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0010_alter_enrollment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_individual",
            field=models.BooleanField(default=False, verbose_name="Lecție individuală"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_recuperare",
            field=models.BooleanField(
                default=False, verbose_name="Lecție de recuperare"
            ),
        ),
    ]
