# Generated by Django 5.2.10 on 2026-08-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0011_lesson_is_individual_lesson_is_recuperare"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="airtable_lectii_ramase",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Lecții rămase din modul (Airtable)"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="airtable_prezente_modul",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Prezențe în modulul curent (Airtable)",
            ),
        ),
    ]
