# Generated by Django 5.2.10 on 2026-08-25 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0012_enrollment_airtable_lectii_ramase_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="scheduled_students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "student"},
                related_name="scheduled_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Elevi programați (specific)",
            ),
        ),
    ]
