# Generated by Django 5.2.10 on 2026-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_platform", "0013_lesson_scheduled_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Programată"),
                    ("ongoing", "În Desfășurare"),
                    ("completed", "Finalizată"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
