# Generated by Django 5.2.10 on 2026-01-15 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0002_module_lessontemplate"),
        (
            "teacher_platform",
            "0002_group_code_group_created_date_group_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="account_created_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Data la care a fost creat contul elevului (editabilă)",
                verbose_name="Data Creare Cont",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="avatar",
            field=models.CharField(
                choices=[("boy", "Avatar Băiat"), ("girl", "Avatar Fată")],
                default="boy",
                help_text="Alege un avatar pentru elev",
                max_length=10,
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profiles",
                to="teacher_platform.group",
                verbose_name="Grupă",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="courses.location",
                verbose_name="Locație",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Băiat"), ("F", "Fată")],
                max_length=1,
                verbose_name="Sex",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_managed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profesor",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="teachers",
                to="courses.location",
                verbose_name="Locații",
            ),
        ),
    ]
