# Generated by Django 5.2.10 on 2026-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_account_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID-ul înregistrării din Airtable (recXXXXXXXXXXXXXX). Cheie de upsert.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Airtable Record ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="airtable_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Arhivat (dispărut din Airtable)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_error",
            field=models.TextField(
                blank=True, verbose_name="Ultima eroare de sincronizare"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "În așteptare"),
                    ("synced", "Sincronizat"),
                    ("error", "Eroare"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status sincronizare",
            ),
        ),
    ]
