# Generated by Django 4.2.8 on 2026-01-03 22:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Grupă de Vârstă')),
                ('min_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(3)], verbose_name='Vârstă Minimă')),
                ('max_age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(18)], verbose_name='Vârstă Maximă')),
            ],
            options={
                'verbose_name': 'Grupă de Vârstă',
                'verbose_name_plural': 'Grupe de Vârstă',
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False, verbose_name='Răspuns')),
            ],
            options={
                'verbose_name': 'Mesaj Contact',
                'verbose_name_plural': 'Mesaje Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu Curs')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preț (RON)')),
                ('frequency', models.CharField(max_length=200, verbose_name='Frecvență')),
                ('group_size', models.IntegerField(verbose_name='Număr Copii în Grupă')),
                ('pdf_presentation', models.FileField(blank=True, upload_to='presentations/', verbose_name='Prezentare PDF')),
                ('projects_link', models.URLField(blank=True, verbose_name='Link Proiecte Copii')),
                ('image', models.ImageField(blank=True, upload_to='courses/', verbose_name='Imagine Curs')),
                ('video_url', models.URLField(blank=True, verbose_name='URL Video')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('featured', models.BooleanField(default=False, verbose_name='Recomandat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.agegroup', verbose_name='Grupă de Vârstă')),
            ],
            options={
                'verbose_name': 'Curs',
                'verbose_name_plural': 'Cursuri',
                'ordering': ['-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume Locație')),
                ('address', models.TextField(verbose_name='Adresă')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='Google Maps Embed Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('is_online', models.BooleanField(default=False, verbose_name='Lecții Online')),
            ],
            options={
                'verbose_name': 'Locație',
                'verbose_name_plural': 'Locații',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Nume Părinte')),
                ('child_name', models.CharField(blank=True, max_length=200, verbose_name='Nume Copil')),
                ('text', models.TextField(verbose_name='Text Testimonial')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='courses.course', verbose_name='Curs')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimoniale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Nume Părinte')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Email Părinte')),
                ('parent_phone', models.CharField(max_length=15, verbose_name='Telefon Părinte')),
                ('child_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(18)], verbose_name='Vârsta Copilului')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Termeni Acceptați')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False, verbose_name='Contactat')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Curs')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.location', verbose_name='Locație')),
            ],
            options={
                'verbose_name': 'Lecție Demo',
                'verbose_name_plural': 'Lecții Demo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='locations',
            field=models.ManyToManyField(to='courses.location', verbose_name='Locații'),
        ),
    ]
