# Generated by Django 5.2.10 on 2026-01-15 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nume Modul")),
                ("description", models.TextField(blank=True, verbose_name="Descriere")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordine"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4A90E2",
                        help_text="Culoare în format hex (ex: #4A90E2)",
                        max_length=7,
                        verbose_name="Culoare Calendar",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                        verbose_name="Curs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modul",
                "verbose_name_plural": "Module",
                "ordering": ["course", "order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="LessonTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nume Lecție")),
                ("description", models.TextField(blank=True, verbose_name="Descriere")),
                (
                    "lesson_steps",
                    models.TextField(
                        blank=True,
                        help_text="Pașii necesari pentru desfășurarea lecției",
                        verbose_name="Pași Lecție",
                    ),
                ),
                (
                    "lesson_plan_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF sau document cu planul lecției (nu poate fi descărcat)",
                        null=True,
                        upload_to="lesson_plans/",
                        verbose_name="Plan de Lecție",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordine"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_templates",
                        to="courses.module",
                        verbose_name="Modul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Șablon Lecție",
                "verbose_name_plural": "Șabloane Lecții",
                "ordering": ["module", "order"],
                "unique_together": {("module", "order")},
            },
        ),
    ]
