# Generated by Django 5.2.10 on 2026-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_module_lessontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="airtable_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="ID Airtable"
            ),
        ),
        migrations.AddField(
            model_name="lessontemplate",
            name="airtable_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="ID Airtable"
            ),
        ),
        migrations.AddField(
            model_name="lessontemplate",
            name="materials",
            field=models.TextField(
                blank=True,
                help_text="Materiale pentru elevi (sincronizate din Airtable)",
                verbose_name="Materiale elevi",
            ),
        ),
        migrations.AddField(
            model_name="lessontemplate",
            name="objectives",
            field=models.TextField(
                blank=True,
                help_text="Obiectivele lecției (sincronizate din Airtable)",
                verbose_name="Obiective",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="airtable_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="ID Airtable"
            ),
        ),
    ]
