# Generated by Django 5.2.10 on 2026-08-03 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_airtable_id_lessontemplate_airtable_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordine"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Milestone")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                (
                    "lesson_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="courses.lessontemplate",
                        verbose_name="Lecție",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone Lecție",
                "verbose_name_plural": "Milestones Lecție",
                "ordering": ["lesson_template", "order"],
            },
        ),
    ]
