# Generated by Django 5.2.10 on 2026-08-04 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirtablePushJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_table",
                    models.CharField(max_length=100, verbose_name="Tabel Airtable"),
                ),
                (
                    "target_record_id",
                    models.CharField(
                        blank=True,
                        help_text="recID existent (update). Gol dacă e create.",
                        max_length=64,
                        verbose_name="Record ID țintă",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, verbose_name="Payload câmpuri"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "În așteptare"),
                            ("done", "Trimis"),
                            ("error", "Eroare"),
                            ("skipped", "Sărit"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Încercări"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Ultima eroare"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creat la"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Procesat la"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Push Airtable",
                "verbose_name_plural": "Joburi Push Airtable",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("pull", "Airtable → Django"),
                            ("push", "Django → Airtable"),
                        ],
                        max_length=10,
                        verbose_name="Direcție",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "În curs"),
                            ("success", "Succes"),
                            ("partial", "Parțial (cu erori)"),
                            ("error", "Eroare"),
                            ("dry_run", "Simulare (dry-run)"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Domeniu"
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(default=False, verbose_name="Simulare"),
                ),
                (
                    "records_created",
                    models.PositiveIntegerField(default=0, verbose_name="Create"),
                ),
                (
                    "records_updated",
                    models.PositiveIntegerField(default=0, verbose_name="Actualizate"),
                ),
                (
                    "records_archived",
                    models.PositiveIntegerField(default=0, verbose_name="Arhivate"),
                ),
                (
                    "records_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Sărite"),
                ),
                (
                    "errors_count",
                    models.PositiveIntegerField(default=0, verbose_name="Erori"),
                ),
                ("details", models.TextField(blank=True, verbose_name="Detalii")),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Pornit la"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminat la"
                    ),
                ),
            ],
            options={
                "verbose_name": "Jurnal Sincronizare",
                "verbose_name_plural": "Jurnale Sincronizare",
                "ordering": ["-started_at"],
            },
        ),
    ]
