# Generated by Django 5.2.10 on 2026-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airtablepushjob",
            name="dedupe_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                verbose_name="Cheie deduplicare",
            ),
        ),
        migrations.AddField(
            model_name="airtablepushjob",
            name="source_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID obiect Django sursă"
            ),
        ),
        migrations.AddField(
            model_name="airtablepushjob",
            name="source_kind",
            field=models.CharField(
                blank=True,
                choices=[("prezenta", "Prezență"), ("lectie", "Lecție finalizată")],
                max_length=20,
                verbose_name="Tip sursă",
            ),
        ),
    ]
